[features]
seeds = true
skip-lint = false
[programs.localnet]
lootbox_program = "2B9axnNZcV4ASAN7eQQFZrEAR7WxkHeNvQFaXc8vE8nF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/James/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
